In [1]:
import numpy as np

In [4]:
nb_x_classes, nb_z_classes = 4, 4

MAP = np.ones((nb_x_classes, nb_x_classes+1), dtype = int)

for x in range(nb_x_classes):
    for s in range(nb_x_classes+1):
        MAP[x][s] = s - 1
        MAP[x][0] = x

In [5]:
print(MAP)

[[0 0 1 2 3]
 [1 0 1 2 3]
 [2 0 1 2 3]
 [3 0 1 2 3]]
