In [1]:
import numpy as np
from numpy import *
import h5py
import scipy.io as sio
from numpy import linalg as LA

In [2]:
def load_PI(name):
    hdf5_path = 'PI/'+name+'.hdf5'
    hdf5_file = h5py.File(hdf5_path, mode='r')
    PI = hdf5_file[name][...]
    hdf5_file.close()
    return PI

In [3]:
def load_channel(true_or_assumed, nb_x_classes, order, PI_type_num):
    PI_dict = sio.loadmat('PARAM/' + true_or_assumed + '_PI.mat')
    PI = PI_dict['%d_%d_%d'%(nb_x_classes, order, PI_type_num)]
    return PI

In [14]:
L1_norm = [[],[],[]]
for i in range(3):
    PI_true = load_channel('true', 2, 1, i)
    if i<2:
        param_name = "ICE_%d_%d_%.2f"%(2, i, 0.1)
    else:
        param_name = "ICE_%d_%d"%(2, i)
    for t in range(10):
        PI = load_PI(param_name + '_%d'%(t-1))
        if t==3:
            print(PI)
        L1_norm[i].append(LA.norm(np.abs(PI-PI_true)) / (4))

[[0.8133446  0.18932822]
 [0.27990186 0.7177562 ]]
[[0.7492309  0.25308713]
 [0.32467073 0.6733974 ]]
[[0.8600777  0.13760568]
 [0.17114474 0.83126765]]


In [5]:
print(L1_norm[0])
print(L1_norm[1])
print(L1_norm[2])

[0.0010966266401343796, 0.013248669012458154, 0.017372846880268633, 0.019154946977994997, 0.01917426600093026, 0.01754544034068553, 0.019070049057008338, 0.02136780564406633, 0.020840512294670648, 0.019998754033334096]
[0.027872733932344046, 0.013191518443344702, 0.010818071444321106, 0.010058245161255893, 0.01030141763674193, 0.011686887151192074, 0.011290821802854508, 0.011814216362637013, 0.010342307137068523, 0.010426402268116345]
[0.021844912734082542, 0.026197421468715287, 0.0308257428699852, 0.029036732885307965, 0.029018243929531572, 0.028030677848160893, 0.0251959782247074, 0.02572156148341377, 0.02867643722043896, 0.029668272676997103]


In [6]:
L1_norm = [[],[],[]]
for i in range(3):
    PI_true = load_channel('true', 2, 1, i)
    for order in range(1,4):
        param_name = "BW_%d_%d_%d"%(2, order, i)
        PI = load_PI(param_name)
        """
        print('type: %d order: %d'%(i,order))
        print(PI)
        """
        L1_norm[i].append(LA.norm(np.abs(PI-PI_true)) / (4))

In [7]:
print(L1_norm[0])
print(L1_norm[1])
print(L1_norm[2])

[0.013662236531811778, 0.013990401167673663, 0.03778702655468827]
[0.0022489751208251644, 0.015408347216406207, 0.05007363114750086]
[0.014852432218021424, 0.025175307502872696, 0.01865851586275508]
